# Generated by Django 4.2.23 on 2025-09-01 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_code', models.CharField(max_length=100, verbose_name='Código del Cliente')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Correo Electrónico de Contacto')),
                ('attachment', models.FileField(upload_to='attachments/', verbose_name='Planilla Adjunta')),
                ('status', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Rechazado', 'Rechazado'), ('Completado', 'Completado')], default='Pendiente', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('created_from_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Creación')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Solicitud de Usuario',
                'verbose_name_plural': 'Solicitudes de Usuario',
                'ordering': ['-created_at'],
            },
        ),
    ]
