# Generated by Django 5.2.5 on 2025-09-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrequest',
            name='attachment',
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='requests_app.userrequest')),
            ],
        ),
    ]
