# Generated by Django 5.2.5 on 2025-09-02 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_remove_userrequest_attachment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
