# Generated by Django 5.2.5 on 2025-09-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_userrequest_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
